# Generated by Django 3.2.13 on 2023-10-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utm_tracker', '0010_auto_20231019_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='course_id',
            field=models.CharField(blank=True, help_text='course_id: The course id of the course ', max_length=250),
        ),
    ]
